# WP Compose with unittest Version 1.2.0

services:
  wordpress:
    image: wp-compose--${DOMAIN:-localhost}--wordpress:${WORDPRESS_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile/wordpress
      args:
        WORDPRESS_IMAGE_TAG: "${WORDPRESS_IMAGE_TAG:-latest}"
        LOOPBACK_IP: "${LOOPBACK_IP:-127.0.0.1}"
        DOMAIN: "${DOMAIN:-localhost}"
        TIMEZONE: "${TIMEZONE:-UTC}"
    container_name: "wp-compose--${DOMAIN:-localhost}--wordpress"
    depends_on:
      database:
        condition: service_started
    restart: always
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:80:80"
      - "${LOOPBACK_IP:-127.0.0.1}:443:443"
    extra_hosts:
      - "${DOMAIN:-localhost}:127.0.0.1"
    links:
      - database
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-database}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-admin}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-wp_}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-true}"
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
      - type: bind
        source: ./src/backup
        target: /var/www/backup
      - type: bind
        source: ./src/import
        target: /var/www/import

      # Set the path of the theme or plugin you are developing and comment it out.
      # - type: bind
      #   source: ./src/themes/YOUR_THEME
      #   target: /var/www/html/wp-content/themes/YOUR_THEME
      # - type: bind
      #   source: ./src/plugins/YOUR_PLUGIN
      #   target: /var/www/html/wp-content/plugins/YOUR_PLUGIN

  database:
    image: "mariadb:${MARIADB_IMAGE_TAG:-latest}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    container_name: "wp-compose--${DOMAIN:-localhost}--database"
    restart: always
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:3306:3306"
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-admin}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/mysql

  wp_cli:
    image: wordpress:cli
    container_name: "wp-compose--${DOMAIN:-localhost}--cli"
    depends_on:
      - wordpress
      - wordpress_unittest
    user: "33:33"
    networks:
      - wordpress
    volumes:
      - type: bind
        source: ./wordpress
        target: /var/www/html
      - type: bind
        source: ./wordpress_e2e
        target: /var/www/html

  mailhog:
    container_name: "wp-compose--${DOMAIN:-localhost}--mailhog"
    image: arjenz/mailhog:latest
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:1025:1025"
      - "${LOOPBACK_IP:-127.0.0.1}:8025:8025"
    networks:
      - wordpress

  wordpress_unittest:
    image: wp-compose--${DOMAIN:-localhost}--wordpress-unittest:${WORDPRESS_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile/wordpress-develop
      args:
        WORDPRESS_IMAGE_TAG: "${WORDPRESS_IMAGE_TAG:-latest}"
        LOOPBACK_IP: "${LOOPBACK_IP_FOR_E2E:-127.0.0.1}"
        DOMAIN: "${DOMAIN_FOR_E2E:-localhost}"
        TIMEZONE: "${TIMEZONE:-UTC}"
    container_name: "wp-compose--${DOMAIN:-localhost}--wordpress-unittest"
    depends_on:
      - database
    restart: always
    ports:
      - "${LOOPBACK_IP_FOR_E2E:-127.0.0.1}:8080:80"
    extra_hosts:
      - "${DOMAIN_FOR_E2E:-localhost}:127.0.0.1"
    links:
      - database
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-database}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}_e2e"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-admin}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-wp_}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-true}"
    volumes:
      - type: bind
        source: ./wordpress_e2e
        target: /var/www/html

      # Set the path of the theme or plugin you are developing and comment it out.
      # - type: bind
      #   source: ./src/themes/YOUR_THEME
      #   target: /var/www/html/wp-content/themes/YOUR_THEME
      # - type: bind
      #   source: ./src/plugins/YOUR_PLUGIN
      #   target: /var/www/html/wp-content/plugins/YOUR_PLUGIN

networks:
  wordpress:
    driver: bridge
