# WP Compose Version 1.0.0

version: '3.9'

services:
  wordpress:
    image: wp-compose--${DOMAIN:-localhost}--wordpress:${WORDPRESS_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile/wordpress
      args:
        WORDPRESS_IMAGE_TAG: "${WORDPRESS_IMAGE_TAG:-latest}"
        LOOPBACK_IP: "${LOOPBACK_IP:-127.0.0.1}"
        DOMAIN: "${DOMAIN:-localhost}"
    container_name: "wp-compose--${DOMAIN:-localhost}--wordpress"
    depends_on:
      database:
        condition: service_started
    restart: always
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:80:80"
      - "${LOOPBACK_IP:-127.0.0.1}:443:443"
    extra_hosts:
      - "${DOMAIN:-localhost}:127.0.0.1"
    links:
      - database
    networks:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-database}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-admin}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-wp_}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-true}"
    volumes:
      - ./wordpress:/var/www/html
      - ./src/backup:/var/www/backup
      - ./src/import:/var/www/import

  database:
    image: "mariadb:${MARIADB_IMAGE_TAG:-latest}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    container_name: "wp-compose--${DOMAIN:-localhost}--database"
    restart: always
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:3306:3306"
    networks:
      - wordpress
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-admin}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
    volumes:
      - ./database:/var/lib/mysql

  wp_cli:
    image: wordpress:cli
    container_name: "wp-compose--${DOMAIN:-localhost}--cli"
    depends_on:
      - wordpress
    user: "33:33"
    networks:
      - wordpress
    volumes:
      - ./wordpress:/var/www/html

  mailhog:
    container_name: "wp-compose--${DOMAIN:-localhost}--mailhog"
    image: arjenz/mailhog:latest
    ports:
      - "${LOOPBACK_IP:-127.0.0.1}:1025:1025"
      - "${LOOPBACK_IP:-127.0.0.1}:8025:8025"
    networks:
      - wordpress

networks:
  wordpress:
    driver: bridge
