# WP Compose version 0.0.1

version: '3.9'

services:
  wordpress:
    image: ${CUSTOM_WORDPRESS_IMAGE_NAME:-wp-compose-wordpress-http}:${WORDPRESS_IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile/wordpress:${WORDPRESS_DOCKERFILE_TAG:-http}
      args:
        WORDPRESS_IMAGE_TAG: "${WORDPRESS_IMAGE_TAG:-latest}"
    container_name: "${CONTAINER_NAME_PREFIX:-wp_compose}_wordpress_${WORDPRESS_DOCKERFILE_TAG:-http}"
    depends_on:
      - database
    restart: always
    ports:
      - "${HOST_WEB_SERVER_PORT:-8080}:80"
      - "${HOST_WEB_SERVER_SSL_PORT:-8443}:443"
    links:
      - database
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST:-database:3306}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME:-wordpress}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER:-admin}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
      WORDPRESS_TABLE_PREFIX: "${WORDPRESS_TABLE_PREFIX:-wp_}"
      WORDPRESS_DEBUG: "${WORDPRESS_DEBUG:-true}"
    volumes:
      # SSL/TLS (https)
      # - ./mkcert/ssl-cert-snakeoil.pem:/etc/ssl/certs/ssl-cert-snakeoil.pem
      # - ./mkcert/ssl-cert-snakeoil.key:/etc/ssl/private/ssl-cert-snakeoil.key

      - ./wordpress:/var/www/html
      - ./backup:/var/www/backup
      - ./import:/var/www/import

  database:
    image: "mariadb:${MARIADB_IMAGE_TAG:-latest}"
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_general_ci"
    container_name: "${CONTAINER_NAME_PREFIX:-wp_compose}_database"
    restart: always
    ports:
      - "${HOST_DB_SERVER_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-admin}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME:-wordpress}"
      MYSQL_USER: "${WORDPRESS_DB_USER:-admin}"
      MYSQL_PASSWORD: "${WORDPRESS_DB_PASSWORD:-admin}"
    volumes:
      - ./database:/var/lib/mysql

  wp_cli:
    image: wordpress:cli
    container_name: "${CONTAINER_NAME_PREFIX:-wp_compose}_cli"
    depends_on:
      - wordpress
    user: "33:33"
    volumes:
      - ./wordpress:/var/www/html
